name: Run Tests
on: push
jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v3
      - name: install python packages
        run: pip install -r requirements.txt --upgrade pip
      - name: run-tests
        working-directory: testing
        run: python -m unittest -v 
      